{
  "name" : "Continuous Integration",
  "on" : {
    "push" : {
      "paths" : [
        "**"
      ]
    },
    "pull_request" : {
      "paths" : [
        "**"
      ]
    }
  },
  "jobs" : {
    "build-ps2" : {
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 30,
      "env" : {
        "HOMEBREW_NO_ANALYTICS" : "1",
        "HOMEBREW_NO_AUTO_UPDATE" : "1",
        "HOMEBREW_NO_INSTALL_UPGRADE" : "1",
        "HOMEBREW_NO_INSTALL_CLEANUP" : "1",
        "CMAKE_GENERATOR" : "Ninja"
      },
      "steps" : [
        {
          "name" : "Make output directory",
          "run" : "mkdir -p output"
        },
        {
          "name" : "Touch file",
          "run" : "touch output/.br-external.mk"
        },
        {
          "name" : "Copy config",
          "run" : "cp .config-ps2 .config"
        },
        {
          "name" : "Compile project",
          "run" : "make -j$(getconf _NPROCESSORS_ONLN)"
        },
        {
          "name" : "Upload artifact",
          "uses" : "actions/upload-artifact@master",
          "with" : {
            "name" : "rootfs-ps2",
            "path" : "output/images/rootfs.cpio.gz"
          }
        }
      ]
    },
    "create-release" : {
      "needs" : [
        "build-ps2"
      ],
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 5,
      "if" : "startsWith(github.ref, 'refs/tags/v')",
      "steps" : [
        {
          "name" : "Download all artifacts",
          "uses" : "actions/download-artifact@v3"
        },
        {
          "name" : "Create release",
          "if" : "startsWith(github.ref, 'refs/tags/v')",
          "uses" : "marvinpinto/action-automatic-releases@latest",
          "with" : {
            "repo_token" : "${{ secrets.GITHUB_TOKEN }}",
            "prerelease" : "${{ contains(github.ref, '-rc') }}",
            "files" : "**/**.gz"
          }
        }
      ]
    }
  }
}
